# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9c70a2f0a0227e8e0bb186dfe76dd1921c3843697331b0cc05a57e12402f249c4c1d0c427458a53bcc78e645d1a0b4e5111c0d7123aaf9ae02bd3bd2761537b

test:
  secret_key_base: 2d0ac2ee44d809fda678ba09e2671bb147f90c333aa0f60d9ba99d94db4c926437ebd3d3be38f04a55b4a0fa07d225544c12142778fc64ca08b34fe357e54011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
